name: 'build and deploy production'

on:
    push: 
        tags:
            - '*'

jobs:
    build-production-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Set nodejs version to 18.x
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
            cache: 'npm'
        
        - run: npm ci
        
        - name: Run build production (create dist production)
          run: npm run build 
    
        - name: upload dist folder artifact
          uses: actions/upload-artifact@v3         
          with:
            name: dist-production
            path: dist